flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Post Content', validators=[DataRequired()])
    submit = SubmitField('Create Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post


main = Blueprint('main', __name__)

@main.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    # posts = Post.query.paginate(page=page, per_page=2)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    # posts = Post.query.all()
    return render_template('home.html', posts=posts, title='rusrom\'s main')

@main.route('/about')
def about():
    return render_template('about.html', title='About rusrom')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm


posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        # post = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create-post.html', title='Create new post', legend='Create New Post', form=form)

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    
    form.title.data = post.title
    form.content.data = post.content
    return render_template('create-post.html', title='Update Post', legend='Update Post', form=form)

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Post "{post.title}" has been deleted!', 'info')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from flaskblog import bcrypt, db
from flaskblog.models import Post, User
from flaskblog.users.forms import LoginForm, RequestResetForm, ResetPasswordForm, SignupForm, UpdateAccountInformationForm
from flaskblog.users.utils import save_avatar, send_reset_email

users = Blueprint('users', __name__)

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = SignupForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! Now you can login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title='Signup New Pythonista', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        flash('Access denied!', 'danger')
    return render_template('login.html', title='Login Pythonista', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountInformationForm()
    if form.validate_on_submit():
        if form.avatar.data:
            avatar_picture = save_avatar(form.avatar.data)
            current_user.avatar = avatar_picture

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Information was Updated', 'info')
        return redirect(url_for('users.account'))
    
    form.username.data = current_user.username
    form.email.data = current_user.email
    avatar_src = url_for('static', filename='images/account/' + current_user.avatar)
    return render_template('account.html', title='Account', avatar_src=avatar_src, form=form)

@users.route('/author/<string:username>')
def author_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query\
        .filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('author-posts.html', posts=posts, user=user, title=f'All posts of {user.username}')

@users.route('/reset-password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Confirmation link has been sent on your email!', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset-request.html', form=form, title='Request Reset Password')

@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_token(token)

    if user is None:
        flash('This is invalid or expired token!', 'warning')
        return redirect(url_for('users.reset_request'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! Now you can login!', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('reset-password.html', form=form, title='Enter new password for your account')

flaskblog/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <h1>About rusrom</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ avatar_src }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.avatar.label() }}
                    {{ form.avatar(class='form-control-file') }}
                    {% if form.avatar.errors %}
                        {% for error in form.avatar.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/author-posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb3">All posts by{{user.username}} ({{posts.total}})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='images/account/' + post.author.avatar) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.author_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    
    {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_number %}
            {%if posts.page == page_number %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.author_posts', username=user.username, page=page_number) }}">{{ page_number }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.author_posts', username=user.username, page=page_number) }}">{{ page_number }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}

flaskblog/templates/create-post.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class='form-control-label') }}
                    {% if form.title.errors %}
                        {{ form.title(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class='form-control-label') }}
                    {% if form.content.errors %}
                        {{ form.content(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='images/account/' + post.author.avatar) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.author_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    
    {% for page_number in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_number %}
            {%if posts.page == page_number %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
            {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_number) }}">{{ page_number }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon shortcut" href="{{ url_for('static', filename='images/site/favicon.ico') }}" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Home page</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">blog(rusrom)</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.signup') }}">Signup</a>
                {% endif %}
                </div>
            </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}
            </div>
            <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login Form</legend>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Signup</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <article class="media content-section">
        <img src="{{ url_for('static', filename='images/account/' + post.author.avatar) }}" alt="" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.author_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                        <button type="submit" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                  <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

flaskblog/templates/reset-password.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class='form-control-label') }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/reset-request.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Signup Form</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class='form-control-label') }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
        </small>
    </div>
{% endblock content %}